<?xml version='1.0' encoding='UTF-8'?>

<!-- =========== FULL CONFIGURATION FILE ================================== -->
<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
${r"<!--"}${facesConfigFile} generated by ${scriptName} version ${scriptVersion} ${r"-->"}
${r"<!--"}Created on ${aDateTime?iso_local}${r"-->"}

<faces-config version="2.0"
    xmlns="http://java.sun.com/xml/ns/javaee" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-facesconfig_2_0.xsd">
 
    <application>
        <resource-bundle>
            <base-name>${bundlePath}${bundleName}</base-name>
            <var>${bundleVar}</var>
        </resource-bundle>
    </application>
    <application>
        <variable-resolver>
	 ${variableResolverClass}
        </variable-resolver>
    </application>
</faces-config>
