<?xml version="1.0" encoding="UTF-8"?>
<!-- =========== Netbeans Project XML File===================== -->
<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
${r"<!--"}project.xml generated by ${scriptName} version ${scriptVersion} ${r"-->"}
${r"<!--"}Created on ${aDateTime?iso_local}${r"-->"}
<project xmlns="http://www.netbeans.org/ns/project/1">
    <type>org.netbeans.modules.web.project</type>
    <configuration>
        <data xmlns="http://www.netbeans.org/ns/web-project/3">
            <name>${webappPathName}</name>
            <minimum-ant-version>1.6.5</minimum-ant-version>
            <web-module-libraries>
                <library dirs="200">
                    <file>${r"${"}libs.apache-commons.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.primefaces-3.0.0.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.jasperreports-3.7.6.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.poi-3.6-20091214.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.log4j-1.2.15.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.apache-commons-exec-1.1.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.xtecuannet-framework.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.groovy-all-1.7.5.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.jdt-compiler-3.1.1.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.jfreechart-10.1.12.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.spring-framework-3.0.6.RELEASE-lib.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.Jackson-2.0.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.xtecuannet-framework-viewcontroller-services.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.iText-2.1.7.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}reference.${modelProject}.jar${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                <library dirs="200">
                    <file>${r"${"}libs.primafaces-utils-springframework-nbsupport.classpath${r"}"}</file>
                    <path-in-war>WEB-INF/lib</path-in-war>
                </library>
                
            </web-module-libraries>
            <web-module-additional-libraries/>
            <source-roots>
                <root id="src.dir"/>
            </source-roots>
            <test-roots>
                <root id="test.src.dir"/>
            </test-roots>
        </data>
        <references xmlns="http://www.netbeans.org/ns/ant-project-references/1">
            <reference>
                <foreign-project>${modelProject}</foreign-project>
                <artifact-type>jar</artifact-type>
                <script>build.xml</script>
                <target>jar</target>
                <clean-target>clean</clean-target>
                <id>jar</id>
            </reference>
           
        </references>
        <spring-data xmlns="http://www.netbeans.org/ns/spring-data/1">
            <config-files>
                <config-file>src/java/${springBackingBeansFile}</config-file>
                <config-file>web/WEB-INF/${remotingFilename}</config-file>
                <config-file>../${modelProject}/src/${springConfigXmlFilename}</config-file>
            </config-files>
            <config-file-groups/>
        </spring-data>
    </configuration>
</project>
