<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
${r"####>"}${configPropsName} generated by ${scriptName} version ${scriptVersion}
${r"####>"}Created on ${aDateTime?iso_local}
${r"#############################################################################"}
dataSource.jndi=${dataSourceName}
jpa.database=${jpaDatabaseName}
jpa.showSql=${showSQL}
jpa.puName=${jpaPuName}
jpa.puName.jndi=${jpaPuNameJndi}
jpa.puName.jndi.full=${jpaPuNameJndiFull}
reports_path=${reportsPath}/
app.default.skin=${webappDefaultSkin}
excel_path=${excelPath}/
postgres_bkp_path=${pgsqlBkpPath}/
postgres_user=${pgsqlUser}
postgres_pass=${pgsqlPass}
postgres_db=${pgsqlDbname}
postgres_filename_base=${pgsqlBkpBaseFilename}
postgres_extension_base=${pgsqlBkpExtension}
postgres_dump_cmd=${pgsqlBkpCmd}
postgres_host=${pgsqlHost}
postgres_port=${pgsqlPort}
XListBean_entities_pkg=${xlistBeanEntitiesPkg}
XListBean_enums_pkg=${xlistBeanEnumPkg}
mailSession.jndi=${mailSessionJndi}
bundleBaseFile=${bundleName}