<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
${r"####>"}${bundleName}.properties generated by ${scriptName} version ${scriptVersion}
${r"####>"}Created on ${aDateTime?iso_local}
${r"#############################################################################"}