<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
${r"<!--"}${log4jConfFilename} generated by ${scriptName} version ${scriptVersion} ${r"-->"}
${r"<!--"}Created on ${aDateTime?iso_local}${r"-->"}

${r"<?xml"} version="1.0" encoding="UTF-8"${r"?>"}
${r"<!"}DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">

    <appender name="default" class="org.apache.log4j.ConsoleAppender">
        <param name="target" value="System.out"/>
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="${r"[%p] %d{dd MMM hh:mm:ss.SSS aa} %t [%c]%n%m%n%n"}"/>
        </layout>
    </appender>

    
    <logger name="com.xtesoft.xtecuannet.framework">
        <level value="info" />
    </logger>

    <logger name="${basePkg}">
        <level  value="info"/>
    </logger>

    <logger name="${baseWebPkg}">
        <level value="info" />
    </logger>
    

    <root>
        <level value="info" />
        <appender-ref ref="default" />
    </root>


</log4j:configuration>