<?xml version="1.0" encoding="UTF-8"?>
<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
${r"<!--"}${jpaConfigFile} generated by ${scriptName} version ${scriptVersion} ${r"-->"}
${r"<!--"}Created on ${aDateTime?iso_local}${r"-->"}
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="${jpaPuName}" transaction-type="JTA">
        <provider>${jpaProvider}</provider>
        <jta-data-source>${dataSourceName}</jta-data-source>
        <#list entities as e>
        <#assign currentName="${FilenameUtils.getBaseName(e.name)}">
        <class>${entitiesPkg}.${currentName}</class>
        </#list>
        <exclude-unlisted-classes>false</exclude-unlisted-classes>
        <properties>
            <property name="eclipselink.target-database" value="${jpaDatabaseName}"/>
            <property name="eclipselink.target-server" value="${jpaTargetServer}"/>
            <property name="eclipselink.cache.type.default" value="Weak"/>
            <property name="eclipselink.cache.size.default" value="0"/>
            <property name="eclipselink.cache.shared.default" value="false"/>
            <property name="eclipselink.weaving" value="true"/>
            <property name="eclipselink.weaving.internal" value="true"/>
            <property name="eclipselink.jdbc.native-sql" value="${showSQL}"/>
            <property name="eclipselink.logging.level" value="FINEST"/>
            <property name="eclipselink.logging.timestamp" value="true"/>
        </properties>
    </persistence-unit>
</persistence>
