<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:util="http://www.springframework.org/schema/util"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
          http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd
          http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.0.xsd
          http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.0.xsd
          http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-3.0.xsd">   
    <#assign aDateTime = .now>
    <#assign aTime = aDateTime?time>

    ${r"<!--"}Generated by ${scriptName} version ${scriptVersion} ${r"-->"}
    ${r"<!--"}Created on ${aDateTime?iso_local}${r"-->"}
    
    <!--START XTECUANNET-FRAMEWORK-CORE-WEB CONFIG DO NOT TOUCH-->
    
    <bean class="org.springframework.beans.factory.config.CustomScopeConfigurer">
        <property name="scopes">
            <map>
                <entry key="view">
                    <bean class="org.primefaces.spring.scope.ViewScope"/>
                </entry>
            </map>
        </property>
    </bean>
    
    <bean id="messageSource"
          class="org.springframework.context.support.ResourceBundleMessageSource">
        <property name="basename">
            <value>${r"${bundleBaseFile}"}</value>
        </property>
    </bean>
    
    <bean id="XBaseBean" class="com.xtesoft.xtecuannet.framework.viewcontroller.beans.XBaseBean" scope="request"/>
    
    <bean id="guestPreferences" class="com.xtesoft.xtecuannet.framework.viewcontroller.beans.GuestPreferences" scope="request"/>
    
    <bean id="XListBean" class="com.xtesoft.xtecuannet.framework.viewcontroller.beans.XListBean" scope="view"/>
    
    <bean id="XReportsBean" class="com.xtesoft.xtecuannet.framework.viewcontroller.reports.XReportsBean" scope="view"/>
    
    
    <!--FINISH XTECUANNET-FRAMEWORK-CORE-WEB CONFIG DO NOT TOUCH-->


    <!--HERE SOME SAMPLE SPRING MANAGED BEANS CONFIG-->
    <!--<bean id="SecUserBean" class="com.marlenlamures.view.beans.SecUserBean" scope="request"/>
    <bean id="PadecimientoBean" class="com.xtesoft.sscsj.viewcontroller.beans.PadecimientoBean" scope="view"/>-->
    <!--HERE_DOWN_PUT_YOUR_SPRING_MANAGED_BEANS_CONFIG-->
    
    

    
</beans>
