<#assign creationDate = .now>
<#assign aTime = creationDate?time>
/**
 * Author 	 :      ${autor}
 * Date          :      ${creationDate?iso_local}
 * Description   :      Fake Entity cfc:  ${cfcName}  for table:  ${cfcSQLTable} 
 * Generated by  :      ${scriptName} version ${scriptVersion}
 * Extends       :      ${extendsCfc}
 **/
component displayname="${cfcName}" hint="${cfcName}" output="false" extends="${extendsCfc}" accessors="true"      
{
    <#list cfcProperties as cfcProperty>
        property name="${cfcProperty.columnName}" displayname="${cfcProperty.columnName}" hint="${cfcProperty.columnName}" type="${cfcProperty.coldfusionType}";
    </#list>
}