<#assign creationDate = .now>
<#assign aTime = creationDate?time>
${r"<!--"}---------------------------------------------------------------------
Author 	 :	${autor}
Date     :	${creationDate?iso_local}
Description :
	Fake Entity cfc:  ${cfcName}  for table:  ${cfcSQLTable} 
        Generated by  ${scriptName} version ${scriptVersion}

extends = ${extendsCfc}

---------------------------------------------------------------------${r"-->"}
component displayname="${cfcName}" hint="${cfcName}" output="false" extends="${extendsCfc}" accessors="true"      
{
    <#list cfcProperties as cfcProperty>
        property name="${cfcProperty.columnName}" displayname="${cfcProperty.columnName}" hint="${cfcProperty.columnName}" type="${cfcProperty.coldfusionType}";
    </#list>
}