<?xml version="1.0" encoding="UTF-8"?>
<!-- =========== Remoting Services Config File============================= -->
<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
${r"<!--"}${remotingFilename} generated by ${scriptName} version ${scriptVersion} ${r"-->"}
${r"<!--"}Created on ${aDateTime?iso_local}${r"-->"}

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.0.xsd
       http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.0.xsd">


    <!--Remoting sample config -->
    <!--<bean name="/RecService" class="org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter">
        <property name="service" ref="RecService"/>
        <property name="serviceInterface" value="sigju.services.RecService"/>
    </bean>-->

</beans>