<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
/*
 * ${entityName}${serviceSuffixNameImpl}.java
 * Generated by ${scriptName} version ${scriptVersion}
 * Created on ${aDateTime?iso_local}
 */


package ${servicesPkgImpl};

import ${entitiesPkg}.${entityName};
import ${servicesPkg}.${entityName}${serviceSuffixName};
import ${parentServiceImportImpl};
import java.io.Serializable;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Repository;


/**
 *
 * @author ${userName}
 */
@Repository
@Transactional
public class ${entityName}${serviceSuffixNameImpl} extends ${parentServiceImpl}<${entityName}> implements ${entityName}${serviceSuffixName},Serializable{
    
    private static final long serialVersionUID = 1L;
    
    public ${entityName}${serviceSuffixNameImpl}(){
        super(${entityName}.class);
    }
}
