<#assign aDateTime = .now>
<#assign aTime = aDateTime?time>
/*
 * ${entityName}${serviceSuffixName}.java
 * Generated by ${scriptName} version ${scriptVersion}
 * Created on ${aDateTime?iso_local}
 */


package ${servicesPkg};

import ${entitiesPkg}.${entityName};
import ${parentServiceImport};


/**
 *
 * @author ${userName}
 */
public interface ${entityName}${serviceSuffixName} extends ${parentService}<${entityName}> {

}
