${r"#======="}${entityName}Bean generated by Xtecuannet-framework-console-utils v${version} at ${currentDatetime}${r"======="}
${r"#======="}${entityName}.xhtml ${r"&"} ${entityName}_form.xhtml${r"======="}
${entityName}_jsf_msg_delete=Se removio un registro de ${entityName} {0}
${entityName}_jsf_msg_save=Se guardo un registro de ${entityName} {0}
${entityName}_jsf_msg_edit=Se actualizo un registro de ${entityName} {0}
${entityName}_jsf_title=Mantto. de entidades ${entityName}
${entityName}_jsf_header=Mantto. de entidades ${entityName}
<#list columnNames as i>
<#if i.name!="serialVersionUID" && i.type.name !="java.util.List">
${entityName}_jsf_${i.name}=${i.name}
</#if>
</#list>
${entityName}_jsf_btn_new=Nuevo
${entityName}_jsf_btn_edit=Editar
${entityName}_jsf_btn_delete=Eliminar
${entityName}_jsf_btn_save=Guardar
${entityName}_jsf_btn_edit=Actualizar
${entityName}_jsf_btn_cancel=Cancelar
${entityName}_jsf_combo_select=Seleccione