<#list entities as e>
<#assign currentName="${FilenameUtils.getBaseName(e.name)}">
${r"#======="}${currentName}Bean generated by Xtecuannet-framework-console-utils v${version} at ${currentDatetime}${r"======="}
${r"#======="}${currentName}.xhtml ${r"&"} ${currentName}_form.xhtml${r"======="}
${currentName}_jsf_msg_delete=Se removio un registro de ${currentName} {0}
${currentName}_jsf_msg_save=Se guardo un registro de ${currentName} {0}
${currentName}_jsf_msg_edit=Se actualizo un registro de ${currentName} {0}
${currentName}_jsf_title=Mantto. de entidades ${currentName}
${currentName}_jsf_header=Mantto. de entidades ${currentName}
<#list columnNames as i>
<#if i.name!="serialVersionUID" && i.type.name !="java.util.List">
${currentName}_jsf_${i.name}=${i.name}
</#if>
</#list>
${currentName}_jsf_btn_new=Nuevo
${currentName}_jsf_btn_edit=Editar
${currentName}_jsf_btn_delete=Eliminar
${currentName}_jsf_btn_save=Guardar
${currentName}_jsf_btn_edit=Actualizar
</#list>
