<#list entities as e>
<#assign currentName="${FilenameUtils.getBaseName(e.name)}">
${r"<!--"}${currentName}Bean generated by Xtecuannet-framework-console-utils v${version} at ${currentDatetime}${r"-->"}
<bean id="${currentName}Bean" class="${appWebPackage}.${currentName}Bean" scope="request"/>
</#list>